// SPDX-License-Identifier: GPL-3.0-only

pragma solidity 0.6.11;

/**
 * @dev Interface of the Validators Registration contract.
 * Interface for sending validator deposit to the registration contract (deployed by Ethereum).
 */
abstract contract IValidatorRegistration {
    /**
    * Function for registering an Ethereum 2.0 validator.
    * @param pubkey - BLS public key of the validator, generated by the operator.
    * @param withdrawCredentials - validator withdrawal credentials.
    * @param signature - BLS signature of the validator, generated by the operator.
    * @param depositDataRoot - hash tree root of the deposit data, generated by the operator.
    */
    function deposit(
        bytes memory pubkey,
        bytes memory withdrawCredentials,
        bytes memory signature,
        bytes32 depositDataRoot
    ) public virtual payable;
}
