pragma solidity 0.5.17;

/**
 * @title VRC interface
 * Interface for sending validator's deposit to the registration contract (deployed by Ethereum).
 */
contract IValidatorRegistration {
    /**
    * Function for registering an Ethereum 2.0 validator.
    * @param pubkey - BLS public key of the validator, generated by the operator.
    * @param withdrawCredentials - validator withdrawal credentials.
    * @param signature - BLS signature of the validator, generated by the operator.
    * @param depositDataRoot - hash tree root of the deposit data, generated by the operator.
    */
    function deposit(
        bytes memory pubkey,
        bytes memory withdrawCredentials,
        bytes memory signature,
        bytes32 depositDataRoot
    ) public payable;
}
