pragma solidity 0.5.10;

/**
 * @title VRC interface
 * Interface for sending validator's deposit to the registration contract (deployed by Ethereum).
 */
contract IValidatorRegistration {
    /**
    * Function for registering an Ethereum Validator.
    * pubkey - BLS public key of the validator, generated by the operator.
    * withdraw_credentials - Validator's withdrawal credentials. Received from Settings contract.
    * signature - BLS signature of the validator, generated by the operator.
    */
    function deposit(bytes memory pubkey, bytes memory withdraw_credentials, bytes memory signature) public payable;
}
